provider:
  name: faas
  gateway: http://127.0.0.1:8080
#some
functions:
  goodfirstissue:
    lang: golang-middleware
    handler: ./goodfirstissue
    image: goodfirstissue:0.1
    secrets:
      - goodfirstissue
